<?php echo $this->doctype(); ?>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
      <!-- Tell the browser to be responsive to screen width -->
      <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no') ?>

      <!-- Le styles -->
      <?php 
        echo $this->headLink(array(
          'rel' => 'shortcut icon',
          'type' => 'image/vnd.microsoft.icon',
          'href' => $this->basePath() . '/images/favicon.ico'
          ))
          ->prependStylesheet($this->basePath() . '/dist/css/skins/_all-skins.min.css')
          ->prependStylesheet($this->basePath() . '/dist/css/AdminLTE.min.css')
          ->prependStylesheet($this->basePath() . '/fonts/ionicons/css/ionicons.min.css')
          ->prependStylesheet($this->basePath() . '/fonts/font-awesome/css/font-awesome.min.css')
          ->prependStylesheet($this->basePath() . '/css/style.css')
          ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
      ?>
      <!-- Scripts -->
      <?php 
          $this->headScript()
          ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',));
      ?>
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
      <!-- Header -->
      <header class="main-header">
        <?=$this->render('layout/header.phtml');?>
      </header>
      <!-- /.main-header -->

      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">
        <?=$this->render('layout/aside.phtml');?>
      </aside>

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <?=$this->render('layout/content.phtml');?>
      </div>
      <!-- /.content-wrapper -->

      <!-- Footer -->
      <footer class="main-footer">
        <?=$this->render('layout/footer.phtml');?>
      </footer>
      <!-- /.main-footer -->

      <!-- Control Sidebar -->
      <aside class="control-sidebar control-sidebar-dark">
        <?=$this->render('layout/control-aside.phtml');?>
      </aside>
      <!-- /.control-sidebar -->

      <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
      <div class="control-sidebar-bg"></div>

    </div>

    <?php
        $this->headScript()     
        ->prependFile($this->basePath() . '/js/jQuery-2.2.0.min.js')
        ->appendFile($this->basePath() . '/js/bootstrap.min.js')
        ->appendFile($this->basePath() . '/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js')
        ->appendFile($this->basePath() . '/plugins/slimScroll/jquery.slimscroll.min.js')
        ->appendFile($this->basePath() . '/plugins/fastclick/fastclick.js')
        ->appendFile($this->basePath() . '/dist/js/app.min.js')
        ->appendFile($this->basePath() . '/dist/js/demo.js');
        echo $this->headScript();
    ?>
  </body>
</html>